"use client";
import { useState } from 'react';
import { fieldTypes, validateParticipant, type BuilderField } from '@/lib/quiz-builder';
export function FieldBuilder({fields,onChange}:{fields:BuilderField[];onChange:(v:BuilderField[])=>void}){
 const [preview,setPreview]=useState(false);
 const update=(i:number,patch:Partial<BuilderField>)=>onChange(fields.map((f,n)=>n===i?{...f,...patch}:f));
 const move=(i:number,delta:number)=>{const next=[...fields];[next[i],next[i+delta]]=[next[i+delta],next[i]];onChange(next);};
 return <div className="stack"><div className="row cms-actions"><button type="button" className="btn btn-outline" onClick={()=>onChange([...fields,{id:crypto.randomUUID(),label:'',key:`field_${fields.length+1}`,type:'text',placeholder:'',required:false,options:[],sort_order:fields.length,is_identifier:false,show_on_leaderboard:false}])}>+ Thêm trường</button><button type="button" className="btn btn-soft" onClick={()=>setPreview(!preview)}>Preview form</button></div>
 {!fields.length&&<p className="muted">Chưa có trường thông tin.</p>}
 {fields.map((f,i)=><section className="admin-card stack" key={f.id}><div className="row-between"><strong>Trường {i+1}</strong><div className="row"><button type="button" className="btn btn-soft" disabled={i===0} onClick={()=>move(i,-1)} aria-label={`Đưa trường ${i+1} lên`}>↑</button><button type="button" className="btn btn-soft" disabled={i===fields.length-1} onClick={()=>move(i,1)} aria-label={`Đưa trường ${i+1} xuống`}>↓</button><button type="button" className="btn btn-ghost" onClick={()=>{if(confirm('Xóa trường này? Thay đổi có hiệu lực khi lưu quiz.'))onChange(fields.filter((_,n)=>n!==i));}}>Xóa</button></div></div><div className="form-grid"><label className="label">Label<input className="input" required value={f.label} onChange={e=>update(i,{label:e.target.value})}/></label><label className="label">Key<input className="input" required pattern="[a-z][a-z0-9_]{0,63}" value={f.key} onChange={e=>update(i,{key:e.target.value})}/></label><label className="label">Loại<select aria-label="Loại" className="select" value={f.type} onChange={e=>update(i,{type:e.target.value as BuilderField['type']})}>{fieldTypes.map(t=><option key={t}>{t}</option>)}</select></label><label className="label">Placeholder<input className="input" value={f.placeholder} onChange={e=>update(i,{placeholder:e.target.value})}/></label></div>
 {['select','radio','checkbox'].includes(f.type)&&<label className="label">Lựa chọn (mỗi dòng một giá trị)<textarea className="textarea" value={f.options.join('\n')} onChange={e=>update(i,{options:e.target.value.split('\n')})}/></label>}
 <div className="row cms-actions"><label><input type="checkbox" checked={f.required} onChange={e=>update(i,{required:e.target.checked})}/> Bắt buộc</label><label><input type="checkbox" checked={f.is_identifier} onChange={e=>update(i,{is_identifier:e.target.checked})}/> Dùng làm định danh</label><label><input type="checkbox" checked={f.show_on_leaderboard} onChange={e=>update(i,{show_on_leaderboard:e.target.checked})}/> Hiển thị trên leaderboard</label></div></section>)}
 {preview&&<section className="admin-card"><h3>Xem trước form</h3><ParticipantPreview fields={fields}/></section>}
 </div>;
}
export function ParticipantPreview({fields}:{fields:BuilderField[]}){
 const [values,setValues]=useState<Record<string,unknown>>({});const [errors,setErrors]=useState<Record<string,string>>({});
 return <div className="stack">{fields.map(f=><div key={f.id}><label className="label" htmlFor={`preview-${f.id}`}>{f.label}{f.required?' *':''}</label>{f.type==='textarea'?<textarea id={`preview-${f.id}`} className="textarea" placeholder={f.placeholder} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>:f.type==='select'?<select id={`preview-${f.id}`} className="select" onChange={e=>setValues({...values,[f.key]:e.target.value})}><option value="">Chọn...</option>{f.options.map((o,i)=><option key={i}>{o}</option>)}</select>:['radio','checkbox'].includes(f.type)?<div role="group" aria-label={f.label}>{f.options.map((o,i)=><label className="row" key={i}><input type={f.type} name={`preview-${f.id}`} onChange={e=>{const list=Array.isArray(values[f.key])?values[f.key] as string[]:[];setValues({...values,[f.key]:f.type==='radio'?o:e.target.checked?[...list,o]:list.filter(v=>v!==o)});}}/>{o}</label>)}</div>:<input id={`preview-${f.id}`} className="input" type={f.type} placeholder={f.placeholder} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>}<span role="status" style={{color:'var(--red)'}}>{errors[f.key]}</span></div>)}<button className="btn btn-outline" type="button" onClick={()=>setErrors(validateParticipant(fields,values))}>Kiểm tra form mẫu</button></div>;
}

