"use client";
import { useState } from 'react';
import { publicQuestion, type BuilderQuestion } from '@/lib/quiz-builder';
export function QuestionBuilder({questions,onChange}:{questions:BuilderQuestion[];onChange:(q:BuilderQuestion[])=>void}){
 const [selected,setSelected]=useState(0);const [preview,setPreview]=useState(false);const current=Math.min(selected,questions.length-1);const q=questions[current];
 const update=(patch:Partial<BuilderQuestion>)=>onChange(questions.map((x,i)=>i===current?{...x,...patch}:x));
 function add(){const first=crypto.randomUUID();onChange([...questions,{id:crypto.randomUUID(),type:'multiple_choice',content:'',points:1,sort_order:questions.length,options:[{id:first,content:''},{id:crypto.randomUUID(),content:''}],correct_option_id:first,correct_boolean:true,accepted_answers:[],case_insensitive:true}]);setSelected(questions.length);}
 function move(delta:number){const next=[...questions];[next[current],next[current+delta]]=[next[current+delta],next[current]];onChange(next);setSelected(current+delta);}
 const safe=q?publicQuestion(q):null;
 return <div className="builder-layout"><aside className="admin-card builder-sidebar stack"><strong>Danh sách câu hỏi</strong>{questions.map((x,i)=><button className={`builder-item ${current===i?'active':''}`} key={x.id} type="button" onClick={()=>setSelected(i)}>{i+1}. {x.content.slice(0,40)||'Câu hỏi mới'}</button>)}<button className="btn btn-outline" type="button" onClick={add}>+ Thêm câu hỏi</button></aside>
 <section className="admin-card stack">{!q?<p>Chưa có câu hỏi. Thêm câu hỏi để bắt đầu.</p>:<><div className="row-between"><h3>Câu {current+1}</h3><div className="row cms-actions"><button className="btn btn-soft" type="button" disabled={current===0} aria-label="Đưa câu hỏi lên" onClick={()=>move(-1)}>↑</button><button className="btn btn-soft" type="button" disabled={current===questions.length-1} aria-label="Đưa câu hỏi xuống" onClick={()=>move(1)}>↓</button><button className="btn btn-ghost" type="button" onClick={()=>{if(confirm('Xóa câu hỏi và đáp án? Thay đổi có hiệu lực khi lưu quiz.'))onChange(questions.filter((_,i)=>i!==current));}}>Xóa</button><button className="btn btn-outline" type="button" onClick={()=>setPreview(!preview)}>Preview</button></div></div>
 <div className="form-grid"><label className="label">Loại câu hỏi<select aria-label="Loại câu hỏi" className="select" value={q.type} onChange={e=>{const type=e.target.value as BuilderQuestion['type'];const first=crypto.randomUUID();update({type,options:type==='multiple_choice'?[{id:first,content:''},{id:crypto.randomUUID(),content:''}]:[],correct_option_id:type==='multiple_choice'?first:'',accepted_answers:[]});}}><option value="multiple_choice">Trắc nghiệm</option><option value="true_false">Đúng / Sai</option><option value="short_answer">Trả lời ngắn</option></select></label><label className="label">Điểm<input className="input" type="number" min="0" max="100000" step="0.01" value={q.points} onChange={e=>update({points:Number(e.target.value)})}/></label></div><label className="label">Nội dung câu hỏi<textarea className="textarea" value={q.content} onChange={e=>update({content:e.target.value})}/></label>
 {q.type==='multiple_choice'&&<div className="stack"><p className="small muted">Chọn đúng một đáp án.</p>{q.options.map((o,i)=><div className="row" key={o.id}><input aria-label={`Đáp án đúng ${i+1}`} type="radio" name={`correct-${q.id}`} checked={q.correct_option_id===o.id} onChange={()=>update({correct_option_id:o.id})}/><input aria-label={`Lựa chọn ${i+1}`} className="input" value={o.content} onChange={e=>update({options:q.options.map(x=>x.id===o.id?{...x,content:e.target.value}:x)})}/><button type="button" className="btn btn-ghost" aria-label={`Xóa lựa chọn ${i+1}`} onClick={()=>{if(confirm('Xóa lựa chọn này?'))update({options:q.options.filter(x=>x.id!==o.id),correct_option_id:q.correct_option_id===o.id?'':q.correct_option_id});}}>×</button></div>)}<button className="btn btn-soft" type="button" disabled={q.options.length>=20} onClick={()=>update({options:[...q.options,{id:crypto.randomUUID(),content:''}]})}>+ Thêm lựa chọn</button></div>}
 {q.type==='true_false'&&<label className="label">Đáp án đúng<select aria-label="Đáp án đúng" className="select" value={String(q.correct_boolean)} onChange={e=>update({correct_boolean:e.target.value==='true'})}><option value="true">Đúng</option><option value="false">Sai</option></select></label>}
 {q.type==='short_answer'&&<><label className="label">Đáp án chấp nhận (mỗi dòng một đáp án)<textarea className="textarea" value={q.accepted_answers.join('\n')} onChange={e=>update({accepted_answers:e.target.value.split('\n')})}/></label><label className="row"><input type="checkbox" checked={q.case_insensitive} onChange={e=>update({case_insensitive:e.target.checked})}/> Không phân biệt hoa thường</label><p className="small muted">Khoảng trắng đầu và cuối được loại bỏ.</p></>}
 {preview&&safe&&<section className="surface" style={{padding:20}}><h3>Xem trước: {safe.content}</h3>{safe.options.length?safe.options.map(o=><label className="option" key={o.id}><input type="radio" name={`preview-question-${q.id}`}/>{o.content}</label>):<input className="input" aria-label="Câu trả lời mẫu" placeholder="Nhập câu trả lời"/>}</section>}
 </>}</section></div>;
}


