"use client";
import { useEffect, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { builderSchema, newQuiz, type QuizBuilderData } from '@/lib/quiz-builder';
import { saveQuiz } from '@/app/admin/quiz-actions';
import { FieldBuilder } from './FieldBuilder';
import { QuestionBuilder } from './QuestionBuilder';
function localDate(iso:string){if(!iso)return '';const d=new Date(iso);if(!Number.isFinite(d.getTime()))return '';return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function QuizEditor({initial,tab='overview'}:{initial?:QuizBuilderData;tab?:string}){
 const router=useRouter();const [quiz,setQuiz]=useState(initial??newQuiz());const [active,setActive]=useState(tab);const [dirty,setDirty]=useState(false);const [notice,setNotice]=useState<{ok:boolean;message:string}>();const [pending,start]=useTransition();
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
 function update(p:Partial<QuizBuilderData>){setQuiz(q=>({...q,...p}));setDirty(true);}
 const text=(key:'title'|'slug'|'description',label:string)=> <label className="label">{label}{key==='description'?<textarea className="textarea" value={quiz[key]} onChange={e=>update({[key]:e.target.value})}/>:<input className="input" value={quiz[key]} onChange={e=>update({[key]:e.target.value})}/>}</label>;
 return <><h1 className="admin-page-title">{quiz.id?'Chỉnh sửa quiz':'Tạo bài kiểm tra'}</h1><form onSubmit={e=>{e.preventDefault();const result=builderSchema.safeParse(quiz);if(!result.success){setNotice({ok:false,message:result.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('\n')});return;}start(async()=>{try{const res=await saveQuiz(result.data);setNotice(res);if(res.ok&&res.quiz){setQuiz(res.quiz);setDirty(false);if(!quiz.id)router.replace(`/admin/quizzes/${res.quiz.id}`);}}catch{setNotice({ok:false,message:'Mất kết nối. Dữ liệu nhập vẫn được giữ, hãy thử lại.'});}});}}>
 <fieldset className="cms-fieldset stack" disabled={pending}><nav className="tabs">{[['overview','Thông tin'],['fields','Form'],['questions','Câu hỏi'],['settings','Cài đặt']].map(([key,label])=><button type="button" className={`tab ${key===active?'active':''}`} key={key} onClick={()=>setActive(key)}>{label}</button>)}{quiz.id&&<button type="button" className="tab" onClick={()=>{if(!dirty||confirm("Bỏ thay đổi chưa lưu để mở trang kết quả?"))router.push(`/admin/quizzes/${quiz.id}/result-page`);}}>Kết quả</button>}</nav>
 {(active==='overview'||active==='settings')&&<div className="grid-2"><section className="admin-card stack">{text('title','Tên bài kiểm tra')}{text('slug','Slug')}{text('description','Mô tả')}<label className="label">Trạng thái<select className="select" value={quiz.status} onChange={e=>update({status:e.target.value as QuizBuilderData['status']})}><option value="draft">Draft</option><option value="published">Published</option><option value="closed">Closed</option></select></label><label className="label">{quiz.has_password?'Thay mật khẩu (để trống để giữ)':'Mật khẩu tùy chọn'}<input className="input" type="password" autoComplete="new-password" value={quiz.password} maxLength={128} onChange={e=>update({password:e.target.value})}/></label>{quiz.has_password&&<label className="row"><input type="checkbox" checked={quiz.remove_password} onChange={e=>update({remove_password:e.target.checked})}/> Xóa mật khẩu hiện tại</label>}</section><section className="admin-card stack">{(['duration_minutes','attempt_limit'] as const).map(key=><label key={key} className="label">{key==='duration_minutes'?'Thời lượng (phút)':'Số lượt làm'} · trống = không giới hạn<input type="number" min="1" step="1" className="input" value={quiz[key]??''} onChange={e=>update({[key]:e.target.value===''?null:Number(e.target.value)})}/></label>)}{(['open_at','close_at'] as const).map(key=><label key={key} className="label">{key==='open_at'?'Thời gian mở':'Thời gian đóng'} (giờ máy của bạn)<input className="input" type="datetime-local" value={localDate(quiz[key])} onChange={e=>update({[key]:e.target.value?new Date(e.target.value).toISOString():''})}/></label>)}{([['show_score','Hiện điểm'],['show_rank','Hiện xếp hạng'],['show_correct_answers','Cho phép hiện đáp án sau khi làm']] as const).map(([key,label])=><label key={key} className="row"><input type="checkbox" checked={quiz[key]} onChange={e=>update({[key]:e.target.checked})}/>{label}</label>)}</section></div>}
 {active==='fields'&&<FieldBuilder fields={quiz.fields} onChange={fields=>update({fields})}/>}
 {active==='questions'&&<QuestionBuilder questions={quiz.questions} onChange={questions=>update({questions})}/>}
 <div className="row cms-actions"><button className="btn btn-primary" type="submit">{pending?'Đang lưu...':'Lưu quiz'}</button><button className="btn btn-outline" type="button" onClick={()=>{if(!dirty||confirm('Bỏ các thay đổi chưa lưu?'))router.push('/admin/quizzes');}}>Về danh sách</button><span className="small muted">{dirty?'Có thay đổi chưa lưu':'Đã đồng bộ'}</span></div></fieldset>
 {notice&&<div className={`cms-toast ${notice.ok?'success':'error'}`} role={notice.ok?'status':'alert'} style={{whiteSpace:'pre-line',maxHeight:'50vh',overflow:'auto'}}>{notice.message}<button type="button" aria-label="Đóng thông báo" onClick={()=>setNotice(undefined)}>×</button></div>}
 </form></>;
}

