"use client";
import { useEffect,useState,useTransition } from 'react';
import { resultDocumentSchema,type AdminResultDocument,type ResultBlock } from '@/lib/result-blocks';
import { saveResultDocument } from '@/app/admin/result-actions';
import { ResultBlocks } from '@/components/quiz/ResultBlocks';
const types=[['text','Text'],['youtube','YouTube'],['external_link','Link'],['button','Button'],['image','Image']] as const;
function localDate(iso:string){if(!iso)return '';const d=new Date(iso);return Number.isNaN(d.getTime())?'':new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function ResultBuilder({initial}:{initial:AdminResultDocument}){
 const [doc,setDoc]=useState(initial);const [selected,setSelected]=useState(0);const [pending,start]=useTransition();const [dirty,setDirty]=useState(false);const [notice,setNotice]=useState<{ok:boolean;message:string}>();const b=doc.blocks[selected];
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 function blocks(next:ResultBlock[]){setDoc({...doc,blocks:next});setDirty(true);}
 function update(patch:Partial<ResultBlock>){blocks(doc.blocks.map((x,i)=>i===selected?{...x,...patch}:x));}
 function move(delta:number){const next=[...doc.blocks];[next[selected],next[selected+delta]]=[next[selected+delta],next[selected]];blocks(next);setSelected(selected+delta);}
 return <><div className="row-between cms-heading"><h2>{doc.title}</h2><button className="btn btn-primary" disabled={pending} onClick={()=>{const parsed=resultDocumentSchema.safeParse(doc);if(!parsed.success){setNotice({ok:false,message:parsed.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('\n')});return;}start(async()=>{try{const result=await saveResultDocument(parsed.data);setNotice(result);if(result.ok&&result.document){setDoc(result.document);setDirty(false);}}catch{setNotice({ok:false,message:'Mất kết nối, vui lòng thử lại.'});}});}}>{pending?'Đang lưu…':'Lưu trang kết quả'}</button></div><p className="small muted">{dirty?'Có thay đổi chưa lưu.':'Đã đồng bộ.'} Nội dung chữa bài có thể thay đổi sau khi đã có người nộp; điểm và bài làm được giữ nguyên.</p>
 <fieldset className="cms-fieldset" disabled={pending}><div className="result-builder"><aside className="admin-card block-library"><strong>NỘI DUNG</strong>{types.map(([type,label])=><button type="button" className="block-button" key={type} onClick={()=>{blocks([...doc.blocks,{id:crypto.randomUUID(),type,title:'',content:'',url:'',visibility:'after_submit',scheduled_at:''}]);setSelected(doc.blocks.length);}}>+ {label}</button>)}<hr/>{doc.blocks.map((x,i)=><button type="button" className={`builder-item ${i===selected?'active':''}`} key={x.id} onClick={()=>setSelected(i)}>{i+1}. {x.title||x.type}</button>)}</aside>
 <main className="admin-card"><div className="preview-phone"><p className="small muted">Preview cấu trúc — số liệu ví dụ, hiển thị toàn bộ block kể cả chưa đến lịch.</p><div className="result-hero"><h3>Hoàn thành bài kiểm tra!</h3>{doc.show_score&&<div className="score-box">18 / 20</div>}<div className="result-stats">{doc.show_score&&doc.show_percentage&&<div>90%</div>}{doc.show_rank&&<div>#12</div>}{doc.show_duration&&<div>06:23</div>}{doc.show_score&&doc.show_correct_count&&<div>18 đúng</div>}{doc.show_score&&doc.show_wrong_count&&<div>2 sai</div>}</div></div><ResultBlocks blocks={doc.blocks}/>{!doc.blocks.length&&<p className="muted">Thêm block từ thư viện nội dung.</p>}</div></main>
 <aside className="admin-card block-settings stack"><strong>CÀI ĐẶT BLOCK</strong>{b?<><div className="row cms-actions"><button type="button" className="btn btn-soft" disabled={selected===0} onClick={()=>move(-1)} aria-label="Đưa block lên">↑</button><button type="button" className="btn btn-soft" disabled={selected===doc.blocks.length-1} onClick={()=>move(1)} aria-label="Đưa block xuống">↓</button><button type="button" className="btn btn-ghost" onClick={()=>{if(confirm('Xóa block này? Thay đổi áp dụng khi lưu.')){blocks(doc.blocks.filter((_,i)=>i!==selected));setSelected(Math.max(0,selected-1));}}}>Xóa block</button></div><label className="label">Tiêu đề<input className="input" maxLength={200} value={b.title} onChange={e=>update({title:e.target.value})}/></label><label className="label">{b.type==='text'?'Nội dung văn bản':'Nhãn / mô tả'}<textarea className="textarea" maxLength={10000} value={b.content} onChange={e=>update({content:e.target.value})}/></label>{b.type!=='text'&&<label className="label">URL<input className="input" type="url" value={b.url} onChange={e=>update({url:e.target.value})} placeholder={b.type==='youtube'?'https://youtube.com/watch?v=...':'https://...'}/></label>}<label className="label">Hiển thị<select aria-label="Hiển thị block" className="select" value={b.visibility} onChange={e=>update({visibility:e.target.value as ResultBlock['visibility']})}><option value="after_submit">Sau khi submit</option><option value="after_quiz_closed">Sau khi quiz đóng</option><option value="scheduled_at">Từ thời điểm...</option></select></label>{b.visibility==='scheduled_at'&&<label className="label">Thời điểm (giờ máy của bạn)<input className="input" type="datetime-local" value={localDate(b.scheduled_at)} onChange={e=>update({scheduled_at:e.target.value?new Date(e.target.value).toISOString():''})}/></label>}</>:<p>Chọn hoặc thêm block.</p>}<hr/><strong>SỐ LIỆU KẾT QUẢ</strong>{([['show_percentage','Tỷ lệ điểm (%)'],['show_correct_count','Số câu đúng'],['show_wrong_count','Số câu sai'],['show_duration','Thời gian làm bài']] as const).map(([key,label])=><label className="row" key={key}><input type="checkbox" checked={doc[key]} onChange={e=>{setDoc({...doc,[key]:e.target.checked});setDirty(true);}}/>{label}</label>)}<p className="small muted">Điểm: {doc.show_score?'bật':'tắt'} · Hạng: {doc.show_rank?'bật':'tắt'} · Chi tiết đáp án: {doc.show_correct_answers?'bật (sau khi đóng quiz)':'tắt'}. Đổi các quyền này trong Cài đặt quiz.</p></aside></div></fieldset>
 {notice&&<div className={`cms-toast ${notice.ok?'success':'error'}`} role={notice.ok?'status':'alert'} style={{whiteSpace:'pre-line'}}>{notice.message}<button type="button" aria-label="Đóng thông báo" onClick={()=>setNotice(undefined)}>×</button></div>}</>;
}
