import { spawn } from 'node:child_process';
import { mkdir,writeFile,rm } from 'node:fs/promises';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import { randomBytes } from 'node:crypto';
import { chromium,expect } from '@playwright/test';
import { finalFixture } from './helpers/final-fixture.mjs';
await rm('artifacts/final-qa/results.json',{force:true});
const fixture=await finalFixture(),{db,state,uploads}=fixture,base='http://127.0.0.1:3361';
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3361'],{env:{...process.env,APP_DATA_MODE:'supabase',NEXT_PUBLIC_SITE_URL:base,NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:3360',NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'final-qa-public',SUPABASE_SERVICE_ROLE_KEY:'final-qa-service',QUIZ_SESSION_SECRET:'final-qa-test-only-secret-at-least-32-characters'},stdio:['ignore','pipe','pipe']});
let browser,activePage;const evidence=[],pageErrors=[];
const largePng=await sharp(randomBytes(1024*1024*3),{raw:{width:1024,height:1024,channels:3}}).png().toBuffer();
assert.ok(largePng.length*2>6*1024*1024 && largePng.length<5*1024*1024);
const png=await sharp({create:{width:32,height:24,channels:3,background:'#1677ff'}}).png().toBuffer();
async function quality(page,name,viewport){
 await page.locator('h1,h2').first().waitFor();if(name==='attempt')await page.locator('.timer').waitFor();await expect(page.getByRole('status').filter({hasText:/^Đang tải/})).toHaveCount(0);await page.evaluate(()=>window.scrollTo(0,0));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const unlabeled=await page.locator('input:not([type=hidden]),select,textarea').evaluateAll(nodes=>nodes.filter(e=>!e.labels?.length&&!e.getAttribute('aria-label')&&!e.getAttribute('aria-labelledby')).map(e=>e.outerHTML));assert.deepEqual(unlabeled,[],name+' labels');
 await page.screenshot({path:`artifacts/final-qa/${name}-${viewport.width}.png`,fullPage:true});
 evidence.push({viewport,screen:name,overflow:false,labels:true});
}
const saveCms=async page=>{await page.getByRole('button',{name:'Lưu thay đổi',exact:true}).click();await page.getByRole('status').filter({hasText:'Đã lưu thay đổi'}).waitFor();};
try{
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('startup timeout')),20000);server.stdout.on('data',b=>{if(String(b).includes('Ready')){clearTimeout(timer);resolve();}});server.once('error',reject);});
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{channel:'chromium'})});
 const createContext=browser.newContext.bind(browser);browser.newContext=async options=>{const c=await createContext(options);c.setDefaultTimeout(15000);c.setDefaultNavigationTimeout(30000);return c;};
 await mkdir('artifacts/final-qa',{recursive:true});
 for(const viewport of [{width:375,height:812},{width:768,height:1024},{width:1440,height:900}]){
  const tag=String(viewport.width),context=await browser.newContext({viewport}),page=await context.newPage();activePage=page;page.on('pageerror',e=>pageErrors.push(e.message));page.on('dialog',d=>d.accept());
  await context.route('https://www.youtube-nocookie.com/**',r=>r.fulfill({contentType:'text/html',body:'<h1>Solution video fixture</h1>'}));
  await context.route('https://www.facebook.com/qa.teacher',r=>r.fulfill({contentType:'text/html',body:'Teacher Facebook fixture'}));
  await page.goto(base+'/admin');await expect(page).toHaveURL(base+'/admin/login');await quality(page,'login',viewport);await page.getByLabel('Email',{exact:true}).focus();await page.keyboard.press('Tab');await expect(page.getByLabel('Mật khẩu',{exact:true})).toBeFocused();assert.equal(await page.getByLabel('Mật khẩu',{exact:true}).evaluate(e=>getComputedStyle(e).outlineStyle),'solid');
  await page.getByLabel('Email',{exact:true}).fill('qa@example.com');await page.getByLabel('Mật khẩu',{exact:true}).fill('wrong');await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Không thể đăng nhập'})).toBeVisible();
  await expect(page.getByLabel('Email',{exact:true})).toHaveValue('qa@example.com');await page.getByLabel('Mật khẩu',{exact:true}).fill('qa-admin-password');state.delayLogin=true;await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await expect(page.getByRole('button',{name:'Đang đăng nhập…'})).toBeDisabled();await page.waitForURL(base+'/admin');state.delayLogin=false;
  assert.ok((await context.cookies()).some(c=>c.name.startsWith('sb-')&&c.httpOnly));await quality(page,'dashboard',viewport);
  await page.goto(base+'/admin/banners/new');await page.getByLabel('Tiêu đề',{exact:true}).fill('QA Banner '+tag);await page.getByLabel('Nội dung nút',{exact:true}).fill('Xem khóa học');await page.getByLabel('URL đích (/path hoặc https://...)',{exact:true}).fill('/search');await page.getByLabel('Hiển thị trên homepage').check();state.delayTable='banners';await page.getByRole('button',{name:'Lưu thay đổi',exact:true}).click();await expect(page.getByRole('button',{name:'Đang lưu...',exact:true})).toBeDisabled();await page.getByRole('status').filter({hasText:'Đã lưu thay đổi'}).waitFor();state.delayTable='';
  const banner=(await db.query('select * from public.banners where title=$1',['QA Banner '+tag])).rows[0];await page.goto(base+'/admin/banners/'+banner.id);await page.getByLabel('Tiêu đề',{exact:true}).fill('QA Banner edited '+tag);await saveCms(page);await quality(page,'banner-edit',viewport);
  await page.goto(base+'/admin/course-sections/new');await page.getByLabel('Tiêu đề',{exact:true}).fill('QA Section '+tag);await page.getByLabel('Hiển thị trên homepage').check();await saveCms(page);const section=(await db.query('select id from public.course_sections where title=$1',['QA Section '+tag])).rows[0].id;
  await page.goto(base+'/admin/courses/new');await page.getByLabel('Tiêu đề',{exact:true}).fill('QA Course '+tag);await page.getByLabel('Slug',{exact:true}).fill('qa-course-'+tag);await page.getByLabel('Nhóm',{exact:true}).selectOption(section);await page.getByLabel('Tên giảng viên',{exact:true}).fill('QA Teacher');await page.getByLabel('Link giảng viên',{exact:true}).fill('https://www.facebook.com/qa.teacher');await page.getByLabel('Hiển thị trên homepage').check();
  await page.locator('input[type=file]').setInputFiles({name:'thumbnail.png',mimeType:'image/png',buffer:png});await saveCms(page);const course=(await db.query('select * from public.courses where slug=$1',['qa-course-'+tag])).rows[0];assert.ok(course.thumbnail_url);assert.ok(uploads.size>0);assert.equal((await sharp([...uploads.values()].at(-1)).metadata()).format,'webp');await quality(page,'course-form',viewport);
  await page.goto(base+'/');await page.getByText('QA Course '+tag,{exact:true}).first().waitFor();await page.getByRole('heading',{name:'QA Banner edited '+tag}).waitFor();await expect.poll(()=>page.locator('.course-card').filter({hasText:'QA Course '+tag}).locator('img').evaluate(e=>e.naturalWidth)).toBeGreaterThan(0);await quality(page,'homepage',viewport);
  const teacher=page.locator('.course-card').filter({hasText:'QA Course '+tag}).getByRole('link',{name:/QA Teacher/});assert.equal(await teacher.getAttribute('href'),'https://www.facebook.com/qa.teacher');assert.match(await teacher.getAttribute('rel'),/noreferrer/);const popupPromise=page.waitForEvent('popup');await teacher.click();const popup=await popupPromise;await popup.waitForLoadState();assert.equal(await popup.evaluate(()=>window.opener),null);await popup.close();
  await page.getByLabel('Tìm khóa học').fill('QA Course '+tag);await page.getByLabel('Tìm khóa học').press('Enter');await page.getByText('QA Course '+tag,{exact:true}).first().waitFor();await quality(page,'search',viewport);
  await page.goto(base+'/search?q=does-not-exist-final-qa');await page.getByText('Không có khóa học phù hợp. Thử từ khóa khác.').waitFor();
  state.delayTable='courses';await page.goto(base+'/',{waitUntil:'commit'});await page.getByRole('status').filter({hasText:'Đang tải nội dung'}).waitFor();await page.getByText('QA Course '+tag,{exact:true}).first().waitFor();state.delayTable='';
  await page.goto(base+'/admin/quizzes/new');await page.getByLabel('Tên bài kiểm tra',{exact:true}).fill('QA Quiz '+tag);await page.getByLabel('Slug',{exact:true}).fill('qa-quiz-'+tag);await page.getByLabel('Mật khẩu tùy chọn',{exact:true}).fill('quiz-password-qa');await page.getByRole('button',{name:'Form',exact:true}).click();
  for(const [label,key,type] of [['Họ tên','name','text'],['Email riêng','email','email'],['Lớp','class','select']]){
   await page.getByRole('button',{name:'+ Thêm trường',exact:true}).click();const card=page.locator('section.admin-card').last();await card.getByLabel('Label',{exact:true}).fill(label);await card.getByLabel('Key',{exact:true}).fill(key);await card.getByLabel('Loại',{exact:true}).selectOption(type);await card.getByLabel('Bắt buộc',{exact:true}).check();if(key==='name')await card.getByLabel('Hiển thị trên leaderboard').check();if(key==='email')await card.getByLabel('Dùng làm định danh').check();if(type==='select')await card.getByLabel('Lựa chọn (mỗi dòng một giá trị)',{exact:true}).fill('A\nB');
  }
  await quality(page,'fields',viewport);await page.getByRole('button',{name:'Câu hỏi',exact:true}).click();
  await page.getByRole('button',{name:'+ Thêm câu hỏi',exact:true}).click();await page.getByLabel('Nội dung câu hỏi',{exact:true}).fill('2 + 2 = ?');await page.getByLabel('Lựa chọn 1',{exact:true}).fill('4');await page.getByLabel('Lựa chọn 2',{exact:true}).fill('5');
  await page.getByRole('button',{name:'+ Thêm câu hỏi',exact:true}).click();await page.getByLabel('Loại câu hỏi',{exact:true}).selectOption('true_false');await page.getByLabel('Nội dung câu hỏi',{exact:true}).fill('Trái đất hình cầu?');
  await page.getByRole('button',{name:'+ Thêm câu hỏi',exact:true}).click();await page.getByLabel('Loại câu hỏi',{exact:true}).selectOption('short_answer');await page.getByLabel('Nội dung câu hỏi',{exact:true}).fill('Thủ đô Việt Nam?');await page.getByLabel('Đáp án chấp nhận (mỗi dòng một đáp án)',{exact:true}).fill('Hà Nội\nHa Noi');await quality(page,'questions',viewport);
  await page.getByRole('button',{name:'Cài đặt',exact:true}).click();await page.getByLabel('Trạng thái',{exact:true}).selectOption('published');await page.getByRole('button',{name:'Lưu quiz',exact:true}).click();await page.waitForURL(/\/admin\/quizzes\/[a-f0-9-]{36}$/);const qid=page.url().split('/').at(-1),slug='qa-quiz-'+tag;
  await page.goto(`${base}/admin/quizzes/${qid}/result-page`);await page.getByRole('button',{name:'+ YouTube',exact:true}).click();await page.getByLabel('Tiêu đề',{exact:true}).fill('Video chữa bài');await page.getByLabel('URL',{exact:true}).fill('https://youtu.be/dQw4w9WgXcQ');await page.getByRole('button',{name:'Lưu trang kết quả',exact:true}).click();await page.getByRole('status').filter({hasText:'Đã lưu trang kết quả.'}).waitFor();await quality(page,'youtube-builder',viewport);
  await page.goto(`${base}/admin/quizzes/${qid}/analytics`);await page.getByText('Chưa có bài nộp để phân tích.').waitFor();
  await page.goto(`${base}/admin/quizzes/${qid}/participants`);await page.getByText('Chưa có dữ liệu phù hợp.').waitFor();
  const student=await browser.newContext({viewport});await student.route('https://www.youtube-nocookie.com/**',r=>r.fulfill({contentType:'text/html',body:'Solution fixture'}));const runner=await student.newPage();runner.on('dialog',d=>d.accept());runner.on('pageerror',e=>pageErrors.push(e.message));
  // Move the database schedule for deterministic boundaries, leaving server authority intact.
  await db.query("update public.quizzes set open_at=now()+interval '1 hour' where id=$1",[qid]);await runner.goto(`${base}/q/${slug}`);await runner.getByText('Bài kiểm tra chưa đến giờ mở.',{exact:true}).waitFor();await quality(runner,'before-open',viewport);
  await db.query("update public.quizzes set open_at=null,close_at=now()-interval '1 second' where id=$1",[qid]);await runner.reload();await runner.getByText('Bài kiểm tra đã đóng.',{exact:true}).waitFor();
  await db.query('update public.quizzes set close_at=null where id=$1',[qid]);await runner.reload();await runner.getByLabel('Mật khẩu bài kiểm tra',{exact:true}).fill('wrong');await runner.getByRole('button',{name:'Mở khóa',exact:true}).click();await expect(runner.getByRole('alert').filter({hasText:'Mật khẩu chưa đúng'})).toBeVisible();await runner.getByLabel('Mật khẩu bài kiểm tra',{exact:true}).fill('quiz-password-qa');await runner.getByRole('button',{name:'Mở khóa',exact:true}).click();await runner.getByLabel('Họ tên *',{exact:true}).waitFor();
  await runner.getByLabel('Họ tên *',{exact:true}).fill('Student '+tag);await runner.getByLabel('Email riêng *',{exact:true}).fill('student'+tag+'@example.com');await runner.getByLabel('Lớp *',{exact:true}).selectOption('A');await quality(runner,'participant-info',viewport);await runner.getByRole('button',{name:'Bắt đầu làm bài',exact:true}).click();await runner.waitForURL(/\/attempt\//);const attempt=runner.url().split('/').at(-1);await quality(runner,'attempt',viewport);
  await expect(runner.getByRole('button',{name:'Câu trước',exact:true})).toBeDisabled();const timer=await runner.locator('.timer').innerText();await expect.poll(()=>runner.locator('.timer').innerText()).not.toBe(timer);
  await runner.getByLabel('4',{exact:true}).check();await runner.getByText('Đã lưu đáp án.',{exact:true}).waitFor();const started=(await db.query('select started_at from public.attempts where id=$1',[attempt])).rows[0].started_at;
  await runner.reload();await expect(runner.getByLabel('4',{exact:true})).toBeChecked();assert.deepEqual((await db.query('select started_at from public.attempts where id=$1',[attempt])).rows[0].started_at,started);
  await runner.getByRole('button',{name:'Câu tiếp',exact:true}).click();await runner.getByLabel('Đúng',{exact:true}).check();await runner.getByRole('button',{name:'Câu tiếp',exact:true}).click();await runner.getByLabel('Câu trả lời',{exact:true}).fill('Hà Nội');await runner.getByText('Đã lưu đáp án.',{exact:true}).waitFor();await expect(runner.getByRole('button',{name:'Câu tiếp',exact:true})).toBeDisabled();
  await runner.getByRole('button',{name:'Nộp bài',exact:true}).click();await runner.waitForURL(/\/result\//);await runner.getByText('3 / 3',{exact:true}).waitFor();await expect(runner.locator('iframe')).toHaveAttribute('src','https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ');await quality(runner,'result',viewport);
  const post=(op,data)=>student.request.post(`${base}/api/quiz/${slug}/${op}`,{headers:{Origin:base},data});for(const response of await Promise.all([post('submit',{attemptId:attempt,answers:{}}),post('submit',{attemptId:attempt,answers:{}})]))assert.equal(response.status(),200);
  assert.equal((await db.query('select count(*)::int n from public.answers where attempt_id=$1',[attempt])).rows[0].n,3);
  const exceeded=await post('start',{requestId:crypto.randomUUID(),participant:{name:'Student '+tag,email:'student'+tag+'@example.com',class:'A'}});assert.equal((await exceeded.json()).error,'ATTEMPT_LIMIT');
  await runner.getByRole('link',{name:'Bảng xếp hạng',exact:true}).click();await runner.getByRole('cell',{name:'Họ tên: Student '+tag,exact:true}).waitFor();assert.ok(!(await runner.content()).includes('student'+tag+'@example.com'));await quality(runner,'public-leaderboard',viewport);
  await page.goto(`${base}/admin/quizzes/${qid}/participants`);await page.getByRole('link',{name:'Chi tiết '+attempt.slice(0,8),exact:true}).click();await page.getByRole('heading',{name:'Câu 3: Thủ đô Việt Nam?',exact:true}).waitFor();await quality(page,'participant-detail',viewport);
  await page.goto(`${base}/admin/quizzes/${qid}/analytics`);await page.getByText('100%',{exact:true}).first().waitFor();await quality(page,'analytics',viewport);
  await page.goto(`${base}/admin/quizzes/${qid}/leaderboard`);await quality(page,'admin-leaderboard',viewport);await page.locator('.table-wrap').first().focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>page.locator('.table-wrap').first().evaluate(e=>e.scrollLeft)).toBeGreaterThan(viewport.width===1440?-1:0);
  await page.goto(base+'/admin/settings');await page.getByLabel('Tên website',{exact:true}).fill('QA School '+tag);await page.getByLabel('Tiêu đề website',{exact:true}).fill('QA SEO '+tag);await page.locator('input[name=logo_file]').setInputFiles({name:'logo.png',mimeType:'image/png',buffer:viewport.width===375?largePng:png});await page.locator('input[name=social_image_file]').setInputFiles({name:'social.png',mimeType:'image/png',buffer:viewport.width===375?largePng:png});await page.getByRole('button',{name:'Lưu cài đặt',exact:true}).click();await page.getByText('Đã lưu cài đặt.',{exact:true}).waitFor();await page.reload();await expect(page.getByLabel('Tên website',{exact:true})).toHaveValue('QA School '+tag);await quality(page,'site-settings',viewport);
  await page.goto(base+'/');await expect(page).toHaveTitle('QA SEO '+tag);await page.getByRole('link',{name:/QA School/}).waitFor();await expect(page.locator('footer')).toContainText('QA School '+tag);
  await page.goto(base+'/admin');await page.getByRole('button',{name:'Đăng xuất',exact:true}).click();await page.waitForURL(base+'/admin/login');await page.goto(base+'/admin/quizzes');await expect(page).toHaveURL(base+'/admin/login');
  await runner.goto(base+'/q/no-such-quiz');await runner.getByRole('heading',{name:'Không tìm thấy bài kiểm tra hoặc bài làm'}).waitFor();await quality(runner,'quiz-404',viewport);
  await runner.goto(base+'/not-a-real-route');await expect(runner.getByText('404',{exact:true})).toBeVisible();
  const timerPage=await student.newPage();await timerPage.goto(`${base}/q/${slug}`);await timerPage.getByLabel('Họ tên *',{exact:true}).fill('Timer');await timerPage.getByLabel('Email riêng *',{exact:true}).fill('timer'+tag+'@example.com');await timerPage.getByLabel('Lớp *',{exact:true}).selectOption('A');await timerPage.getByRole('button',{name:'Bắt đầu làm bài',exact:true}).click();await timerPage.waitForURL(/\/attempt\//);const timerId=timerPage.url().split('/').at(-1);timerPage.on('dialog',d=>d.accept());await db.query("update public.attempts set expires_at=now()+interval '3 seconds' where id=$1",[timerId]);await timerPage.reload();await timerPage.waitForURL(/\/result\//);assert.equal((await db.query('select timed_out from public.attempts where id=$1',[timerId])).rows[0].timed_out,true);
  await student.close();await context.close();console.log(`PASS full lifecycle ${viewport.width}x${viewport.height}`);
 }
 // Inject server outage: public content must show a recoverable error, not fixture fallback.
 const errorContext=await browser.newContext(),errorPage=await errorContext.newPage();activePage=errorPage;state.failTable='courses';await errorPage.goto(base+'/');await errorPage.getByRole('heading',{name:'Không thể tải nội dung',exact:true}).waitFor();state.failTable='';await errorPage.getByRole('button',{name:'Thử lại',exact:true}).click();await errorPage.getByRole('link',{name:/QA School/}).waitFor();await errorContext.close();
 assert.deepEqual(pageErrors,[]);
 await writeFile('artifacts/final-qa/results.json',JSON.stringify({status:'PASS',baseCommit:'d4ccb04',viewports:[{width:375,height:812},{width:768,height:1024},{width:1440,height:900}],screens:evidence,limitations:['Local Auth/Storage emulators and PostgreSQL WASM; not live Supabase','Real multi-connection PostgreSQL contention not tested']},null,2));
 console.log('PASS final QA: Admin auth/CMS/settings, public quiz lifecycle, reports, exact viewports, labels, keyboard table scroll, server error/recovery.');
}catch(e){if(activePage){await activePage.screenshot({path:'artifacts/final-qa/failure.png',fullPage:true}).catch(()=>{});console.error((await activePage.locator('body').innerText().catch(()=>'' )).slice(-4000));}console.error(e);throw e;}finally{await browser?.close();server.kill();await fixture.close();}
