"use client";
import { useCallback,useEffect,useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import type { Answers,AttemptData } from '@/lib/public-quiz';
import { quizPost } from './QuizEntry';
export function AttemptRunner({slug,initial}:{slug:string;initial:AttemptData}){
 const router=useRouter();
 const [answers,setAnswers]=useState<Answers>(initial.answers);const [index,setIndex]=useState(0);const [notice,setNotice]=useState('Đáp án được lưu tự động.');const [busy,setBusy]=useState(false);const [remaining,setRemaining]=useState<number|null>(initial.expires_at?Math.max(0,Date.parse(initial.expires_at)-Date.parse(initial.server_now)):null);const latest=useRef(initial.answers);const pending=useRef(false);const submitted=useRef(false);const queue=useRef<Promise<unknown>>(Promise.resolve());const due=useRef(initial.expires_at?Date.parse(initial.expires_at)-Date.parse(initial.server_now):null);const anchor=useRef(0);const [review,setReview]=useState<string[]>([]);
 const resultUrl=`/q/${slug}/result/${initial.id}`;
 const send=useCallback((op:'save'|'submit')=>{
  const task=()=>quizPost(slug,op,{attemptId:initial.id,answers:latest.current}).then((data:AttemptData)=>{if(data.status==='submitted'){submitted.current=true;router.replace(resultUrl);}return data;});
  const job=queue.current.catch(()=>{}).then(task);queue.current=job;return job;
 },[initial.id,resultUrl,slug,router]);
 const submit=useCallback(async()=>{if(pending.current||submitted.current)return;pending.current=true;setBusy(true);setNotice('Đang nộp bài…');try{await send('submit');}catch(e){setNotice(e instanceof Error?e.message:'Nộp bài thất bại. Hãy thử lại.');pending.current=false;setBusy(false);}},[send]);
 useEffect(()=>{anchor.current=performance.now();const timer=setInterval(()=>{if(due.current!==null){const left=Math.max(0,due.current-(performance.now()-anchor.current));setRemaining(left);if(left===0)void submit();}},1000);return()=>clearInterval(timer);},[submit]);
 useEffect(()=>{if(answers===initial.answers)return;const timer=setTimeout(()=>{if(!pending.current&&!submitted.current){setNotice('Đang lưu…');void send('save').then(()=>setNotice('Đã lưu đáp án.')).catch(e=>setNotice(e instanceof Error?e.message:'Chưa lưu được. Giữ trang mở và thử lại.'));}},500);return()=>clearTimeout(timer);},[answers,initial.answers,send]);
 useEffect(()=>{const timer=setInterval(()=>{if(!pending.current&&!submitted.current)void fetch(`/api/quiz/${slug}/get?attemptId=${initial.id}`,{cache:'no-store'}).then(async response=>{if(!response.ok)return;const data=await response.json() as AttemptData;if(data.status==='submitted'){submitted.current=true;router.replace(resultUrl);}else if(data.expires_at){due.current=Date.parse(data.expires_at)-Date.parse(data.server_now);anchor.current=performance.now();}}).catch(()=>{});},15000);return()=>clearInterval(timer);},[initial.id,resultUrl,slug,router]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(!submitted.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 const q=initial.questions[index];if(!q)return <p>Không có câu hỏi.</p>;
 function answer(value:string|boolean|null){const next={...latest.current,[q.id]:value};latest.current=next;setAnswers(next);}
 const seconds=remaining===null?null:Math.ceil(remaining/1000);
 return <main className="quiz-shell"><div className="quiz-topbar"><strong>{initial.title}</strong><div className="row cms-actions"><span className="timer" aria-live="off">{seconds===null?'Không giới hạn':`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}</span><button disabled={busy} className="btn btn-primary" onClick={()=>{if(confirm('Nộp bài? Bạn không thể sửa sau khi nộp.'))void submit();}}>Nộp bài</button></div></div><p role="status">{notice}</p><div className="quiz-workspace"><aside className="surface question-nav"><strong>Câu hỏi</strong><div className="question-grid">{initial.questions.map((x,i)=><button key={x.id} className={`qnum ${index===i?'current':answers[x.id]!==undefined&&answers[x.id]!==null&&answers[x.id]!==''?'done':''}`} onClick={()=>setIndex(i)} aria-label={`Câu ${i+1}${review.includes(x.id)?', đánh dấu xem lại':''}`}>{i+1}{review.includes(x.id)?'★':''}</button>)}</div><p className="small muted">★ Cần xem lại</p></aside><section className="surface question-panel stack"><h2>Câu {index+1} · {q.points} điểm</h2><p>{q.content}</p><fieldset disabled={busy} className="cms-fieldset stack">{q.type==='short_answer'?<label className="label">Câu trả lời<input className="input" maxLength={2000} value={typeof answers[q.id]==='string'?answers[q.id] as string:''} onChange={e=>answer(e.target.value)}/></label>:q.options.map(o=>{const value=q.type==='true_false'?o.id==='true':o.id;return <label key={o.id} className={`option ${answers[q.id]===value?'selected':''}`}><input type="radio" name={q.id} checked={answers[q.id]===value} onChange={()=>answer(value)}/>{o.content}</label>;})}<div className="row cms-actions"><button type="button" className="btn btn-ghost" onClick={()=>answer(null)}>Xóa lựa chọn</button><label><input type="checkbox" checked={review.includes(q.id)} onChange={e=>setReview(e.target.checked?[...review,q.id]:review.filter(id=>id!==q.id))}/> Đánh dấu xem lại</label></div></fieldset><div className="row-between"><button className="btn btn-outline" disabled={index===0} onClick={()=>setIndex(index-1)}>Câu trước</button><button className="btn btn-primary" disabled={index===initial.questions.length-1} onClick={()=>setIndex(index+1)}>Câu tiếp</button></div><button className="btn btn-soft" disabled={busy} onClick={()=>{void send('save').then(()=>setNotice('Đã lưu đáp án.')).catch(e=>setNotice(e.message));}}>Lưu lại ngay</button></section></div></main>;
}

